export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
export const SET_VIEW_INDEX = "SET_VIEW_INDEX";

export const SET_FILTER = "SET_FILTER";
